name: "first experiment"
dataset: "MNIST"
image_channels: 1

diffusion_type: "pixel"
n_steps: 100 # T
n_samples: 16 #number of generated examples after training

data_path: 'data'
logs_path: 'logs'
models_path: 'models'
results_path: 'results'

# training specifics
batch_size: 8
epochs: 5
learning_rate: 0.005

# model specifics
channel_multipliers: [1, 2, 4, 8] #64, 128, 256, 512, etc.
image_size: 64 #for image rescaling
n_channels: 64 #first feature map output channels
out_channels: 1 #noise prediction
with_time_emb: True

