# Train or sample from a pixel based diffusion model
name: "pixel_diffusion_model"
type: pixel
testing: True
diffusion:
  type: pixel
  n_steps: 10 # T (100-400)
  n_samples: 4 #number of generated examples after training
batch_size: 1
epochs: 5
learning_rate: 0.005
loss_fn: mse
model: 
  target: src.UNet.UNet
  params:
    in_channels: 1
    out_channels: 1 #noise prediction
    channels: 64 #first feature map output channels
    channel_multipliers: [1, 2, 4, 8] #64, 128, 256, 512, etc.
    with_time_emb: True
    num_classes: 10
data:
  dataset: "MNIST"
  image_channels: 1
  image_size: 16 #for image rescaling
