# Train or sample from a pixel based diffusion model
project_name: pixel_diffusion_model_mnist_img32
entity: itu-gen
type: pixel
debugging: False
diffusion:
  type: pixel
  target: src.DDPM.Diffusion
  cfg_scale: 3
  params:
    n_steps: 400 # T (100-400)
    n_samples: 100 #number of generated examples after training
    device: cuda
batch_size: 64
epochs: 100 # 100
lr: 0.0005
use_amp: True
loss_fn: mse
early_stopping_patience: 10
model: 
  target: src.UNet.UNet
  params:
    in_channels: 1
    out_channels: 1 #noise prediction
    channels: 64 #first feature map output channels
    channel_multipliers: [1, 2, 4, 8] #64, 128, 256, 512, etc.
    with_time_emb: True
    num_classes: 10
data:
  dataset: MNIS
  image_channels: 1
  image_size: 32 #for image rescaling
  val_split: 0.1
