# Train or sample from a pixel based diffusion model
name: "pixel_diffusion_model_celebA_img64"
type: pixel
testing: False
diffusion:
  type: pixel
  target: src.DDPM.Diffusion
  params:
    n_steps: 400 # T (100-400)
    n_samples: 100 #number of generated examples after training
    device: cuda
batch_size: 64
epochs: 100
learning_rate: 0.0005
loss_fn: mse
model: 
  target: src.UNet.UNet
  params:
    in_channels: 3
    out_channels: 3 #noise prediction
    channels: 64 #first feature map output channels
    channel_multipliers: [1, 2, 4, 8] #64, 128, 256, 512, etc.
    with_time_emb: True
    num_classes: 10
data:
  dataset: CIFAR10
  image_channels: 3
  image_size: 32 #for image rescaling
