# Train a resnet classifier
project_name: resnet_testing_2
entity: itu-gen
type: resnet
debugging: True
batch_size: 64
epochs: 5
lr: 0.0001
use_amp: True
loss_fn: cross-entropy
early_stopping_patience: 10
model: 
  target: src.ResNetClassifier.ResNetBase
  params:
    img_channels: 3 # MNIST is gray-scale
    out_channels: 10 # 10 classes in CIFAR10
    n_blocks: [2, 2, 2, 2]
    n_channels: [64, 128, 256, 512] 
data:
  dataset: CIFAR10
  image_channels: 3
  image_size: 64
  val_split: 0.1
pretrain: False
synthetic_data:
  path: pixel/pixel_diffusion__CIFAR10_img64/results

